front/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.board_list, name='board_list'),
    url(r'^board/(?P<pk>\d+)/$', views.board_detail, name='board_detail'),
    url(r'^board/new/$', views.board_new, name='board_new'),
    url(r'^board/(?P<pk>\d+)/edit$', views.board_edit, name='board_edit'),
    url(r'^board/(?P<pk>\d+)/destroy$', views.board_destroy, name='board_destroy'),
    url(r'^list/new/$', views.list_new, name='list_new'),
    url(r'^list/(?P<pk>\d+)/edit$', views.list_edit, name='list_edit'),
    url(r'^list/(?P<pk>\d+)/destroy$', views.list_destroy, name='list_destroy'),
    url(r'^bookmark/new/$', views.bookmark_new, name='bookmark_new'),
    url(r'^bookmark/(?P<pk>\d+)/edit$', views.bookmark_edit, name='bookmark_edit'),
    url(r'^bookmark/(?P<pk>\d+)/destroy$', views.bookmark_destroy, name='bookmark_destroy'),
]

hou/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('front.urls')),
]

front/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=20, null=False)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class List(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=20, null=False)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Bookmark(models.Model):
    list = models.ForeignKey(List, on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=200, null=False)
    url = models.CharField(max_length=200,null=False)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

front/forms.py
from django import forms

from .models import *

class BoardForm(forms.ModelForm):

    class Meta:
        model = Board
        fields = ('title', )

class ListForm(forms.ModelForm):

    class Meta:
        model = List
        fields = ('title', )

class BookmarkForm(forms.ModelForm):

    class Meta:
        model = Bookmark
        fields = ('title', 'url', 'list')
        widgets = {
            'title' : forms.TextInput(attrs={'class' : 'form-control'}),
            'url' : forms.TextInput(attrs={'class' : 'form-control'}),
            'list' : forms.Select(attrs={'class' : 'form-control'})
        }

front/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.http import HttpResponse
import json

from .models import *
from .forms import *

# views : board
def board_list(request):
    boards = Board.objects.filter(created_date__lte=timezone.now()).order_by('created_date')
    return render(request, 'board/board_list.html', {'boards' : boards})

def board_detail(request, pk):
    board = get_object_or_404(Board, pk = pk)

    # lists = List.objects.filter(board = board, created_date__lte=timezone.now()).order_by('created_date')
    lists = board.list_set.all()

    return render(request, 'board/board_detail.html', {'board' : board, 'lists' : lists})

def board_new(request):
    if request.method == "POST":
        form = BoardForm(request.POST)

        if form.is_valid():
            board = form.save()

            new_list = List(title="No title", board = board, created_date = timezone.now())
            new_list.save()

            return redirect('board_detail', pk=board.pk)
    else:
        form = BoardForm()

    return render(request, 'board/board_form.html', {'form' : form})

def board_edit(request, pk):
    board = get_object_or_404(Board, pk = pk)

    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)

        if form.is_valid():
            board = form.save()

            return redirect('board_detail', pk=board.pk)
    else:
        form = BoardForm(instance=board)

    return render(request, 'board/board_form.html', {'form' : form})

def board_destroy(request, pk):
    board = get_object_or_404(Board, pk = pk)
    board.delete()

    return redirect('board_list')


# views : list
def list_new(request):
    if request.method == "POST":
        title  = request.POST.get('title')
        board = Board.objects.get(pk=request.POST.get('board_id'))
        created_date = timezone.now()

        new_list = List(title = title, board = board, created_date =  created_date)
        new_list.save()

    html = render_to_string('list/_list.html', {'list' : new_list})

    return HttpResponse(json.dumps(html), content_type='application/json')

def list_edit(request, pk):
    edit_list = get_object_or_404(List, pk = pk)

    if request.method == "POST":
        form = ListForm(request.POST, instance=edit_list)

        if form.is_valid():
            edit_list = form.save()

            return redirect('board_detail', pk=edit_list.board.pk)
    else:
        form = ListForm(instance=edit_list)

    return render(request, 'list/list_form.html', {'form' : form})

def list_destroy(request, pk):
    del_list = get_object_or_404(List, pk = pk)
    board_id = del_list.board.pk

    if del_list.title != "No title":
        del_list.delete()
    else:
        message = "You don't destroy this list"

    return redirect('board_detail', pk=board_id)

# views : bookmark
def bookmark_new(request):

    if request.method == "POST":
        form = BookmarkForm(request.POST)

        if form.is_valid():
            bookmark = form.save()

            return redirect('board_detail', pk=bookmark.list.board.pk)
    else:
        form = BookmarkForm()

    return render(request, 'bookmark/bookmark_form.html', {'form' : form})

def bookmark_edit(request, pk):
    edit_bookmark = get_object_or_404(Bookmark, pk = pk)

    if request.method == "POST":
        form = BookmarkForm(request.POST, instance=edit_bookmark)

        if form.is_valid():
            edit_bookmark = form.save()

            return redirect('board_detail', pk=edit_bookmark.list.board.pk)
    else:
        form = BookmarkForm(instance=edit_bookmark)

    return render(request, 'bookmark/bookmark_form.html', {'form' : form})

def bookmark_destroy(request, pk):
    del_bookmark = get_object_or_404(Bookmark, pk = pk)
    board_id = del_bookmark.list.board.pk

    del_bookmark.delete()


    return redirect('board_detail', pk=board_id)

front/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>HOU!</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
	  <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
	  <link href="{% static 'assets/css/paper-kit.css' %}" rel="stylesheet"/>

    <!--     Fonts and icons     -->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,300,700" rel='stylesheet' type='text/css'>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet" />

    <!-- Core JS Files -->
    <script src="{% static 'assets/js/jquery-3.2.1.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/jquery-ui-1.12.1.custom.min.js' %}" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>

    <!-- Switches -->
    <script src="{% static 'assets/js/bootstrap-switch.min.js' %}"></script>

    <!--  Plugins for Slider -->
    <script src="{% static 'assets/js/nouislider.js' %}"></script>

    <!--  Plugins for DateTimePicker -->
    <script src="{% static 'assets/js/moment.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap-datetimepicker.min.js' %}"></script>

    <!--  Paper Kit Initialization and functons -->
    <script src="{% static 'assets/js/paper-kit.js' %}"></script>

  </head>
  <body>

    {% block content %}
    {% endblock %}


  </body>
</html>

front/templates/board/board_detail.html
{% extends 'base/base.html' %}

{% block content %}

    <div class="container">
      <div class="title">
        <h1>{{board.title}}</h1>
      </div>
    </div>

    <!-- list create form -->
    <div class="container">
      <form id="new_list" class="">
        <div class="row form-group">
          <div class="col-offset-1 col-8">
            <input type="text" class="form-control" id="new_list_title" maxlength="20" placeholder="List title" required>
          </div>

          <div class="col-offset-1 col-1">
            <button type="submit" class="btn btn-default">Save</button>
          </div>
        </div>
      </form>
    </div>

    {% include 'bookmark/_bookmark_new.html' with lists=lists %}

    <div class="container" id="lists">
      {% for list in lists %}
        {% include 'list/_list.html' with list=list %}
      {% endfor %}
    </div>

    <script type="text/javascript">
      var newListForm = $('#new_list');

      newListForm.on('submit', function(event) {
        event.preventDefault();

        $.ajax({
          url: "{% url 'list_new' %}",
          type: "POST",
          dataType: "json",
          data: {
            "title": $("#new_list_title").val(),
					  "board_id": "{{ board.id }}",
            "csrfmiddlewaretoken": "{{ csrf_token }}"
          },
          success: function(data){
            $('#lists').append(data);
            $("#new_list_title").val('');
            alert("Success : List create");
          },
          error:function(){
            alert("Error : List create");
          }
        });
      });

      $(document).ready(function () {
        $(".active_new_bookmark_form").on("click", function () {
          var listId = $(this).data('id');
          console.log(listId);
          $("#new_bookmark_modal #id_list").val(listId);
        });
      });
    </script>
{% endblock %}

front/templates/board/board_form.html
{% extends 'base/base.html' %}

{% block content %}

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
  </form>
{% endblock %}

front/templates/board/board_list.html
{% extends 'base/base.html' %}

{% block content %}

  <div class="container">
    <div class="title">
      <h1>Board List <a class="btn btn-outline-default btn-just-icon btn-sm" href="{% url 'board_new' %}"><i class="fa fa-plus"></i></a></h1>
    </div>

    <div id="board_list" class="row">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Created_date</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for board in boards %}
            <tr>
              <th scope="row">{{ board.id }}</th>
              <td><a class="" href="{% url 'board_detail' pk=board.pk %}">{{ board.title }}</a></td>
              <td>{{ board.created_date }}</td>
              <td>
                <a class="btn btn-link btn-info btn-just-icon btn-sm" href="{% url 'board_edit' pk=board.pk %}"><i class="fa fa-pencil"></i></a>
                <a class="btn btn-link btn-danger btn-just-icon btn-sm" href="{% url 'board_destroy' pk=board.pk %}"><i class="fa fa-trash"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

{% endblock %}

front/templates/board/board_new.html
{% extends 'base/base.html' %}

{% block content %}
  <h1> New Board </h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
  </form>
{% endblock %}

front/templates/bookmark/_bookmark.html
<th scope="row">{{ bookmark.id }}</th>
<td><a href="">{{ bookmark.title }}</a></td>
<td>{{ bookmark.url }}</td>
<td>
  <a class="btn btn-link btn-info btn-just-icon btn-sm" href="{% url 'bookmark_edit' pk=bookmark.id %}"><span class="fa fa-pencil"></span></a>
  <a class="btn btn-link btn-danger btn-just-icon btn-sm" href="{% url 'bookmark_destroy' pk=bookmark.id %}"><span class="fa fa-trash"></span></a>
</td>

front/templates/bookmark/_bookmark_new.html
<div class="modal fade" id="new_bookmark_modal" tabindex="-1" role="dialog" aria-labelledby="new_bookmark_modal_label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="new_bookmark_modal_label"> New Bookmark </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form class="" action="{% url 'bookmark_new'%}" method="post">
              <div class="modal-body">
                {% csrf_token %}
                
                <div class="form-group">
                  <label for="id_title">Title</label>
                  <input type="text" name="title" class="form-control" maxlength="200" required="" id="id_title">
                </div>

                <div class="form-group">
                  <label for="id_url">Url</label>
                  <input type="text" name="url" class="form-control" maxlength="200" required="" id="id_url">
                </div>

                <div class="form-group">
                  <select name="list" class="form-control" required="" id="id_list">
                    {% for list in lists %}
                      <option value="{{ list.id }}">{{ list.title }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <div class="modal-footer">
                  <div class="left-side">
                      <button type="button" class="btn btn-default btn-link" data-dismiss="modal">Close</button>
                  </div>
                  <div class="divider"></div>
                  <div class="right-side">
                      <button type="submit" class="btn btn-danger btn-link">Submit</button>
                  </div>
              </div>
            </form>
        </div>
    </div>
</div>

front/templates/bookmark/bookmark_form.html
{% extends 'base/base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
      </form>
    </div>
  </div>

{% endblock %}

front/templates/list/_list.html
<div class="row">
    <h3>
      {{ list.title }}
    </h3>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">URL</th>
          <th scope="col"><a class="text-info active_new_bookmark_form" data-toggle="modal" data-id="{{ list.id }}" href="#new_bookmark_modal"> <i class='fa fa-plus'></i> ADD BOOKMARK</a></th>
        </tr>
      </thead>
      <tbody>
        {% for bookmark in list.bookmark_set.all %}
          <tr>
            {% include 'bookmark/_bookmark.html' with bookmark=bookmark %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
</div>

front/templates/list/_list_new.html
<th scope="row">{{ list.id }}</th>
<td><a href="">{{ list.title }}</a></td>
<td>{{ list.created_date }}</td>
<td>
  <a class="btn btn-primary btn-sm" href=""><span class="fa fa-pencil"></span></a>
  <a class="btn btn-danger btn-sm" href=""><span class="fa fa-trash"></span></a>
</td>

front/templates/list/list_form.html
{% extends 'base/base.html' %}

{% block content %}

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
  </form>
{% endblock %}